POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4uZG9lIiwiaWQiOiI2NDc3MDMwMTk5MGM5M2IwZjExNWVkNGEiLCJpYXQiOjE2ODU1MjcxNjV9.URF42HxyrLBW6Uxa7DMG5Xe5wqooUBB1GJEnjAnigMQ

{
  "title": "Absalom, Absalom!",
  "author": "William Faulkner",
  "url": "https://www.thriftbooks.com/w/absalom-absalom-by-william-faulkner/249203/?clickref=1100lwNWFkX6",
  "likes": 100,
  "userId": "647706821323ed25e0dcd4ba"
}