DELETE http://localhost:3003/api/blogs/64771f2cbc4cfb59401ca886
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4uZG9lIiwiaWQiOiI2NDc3MDMwMTk5MGM5M2IwZjExNWVkNGEiLCJpYXQiOjE2ODU1ODc0MzJ9.jg6BxqNeRKw4kj61S3GIbVYpkDRd5cjbMtHkrKSIxww